AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

inherit_gem:
  foobara-rubocop-rules:
    - rules/*

Naming/FileName:
  inherit_mode:
    merge:
      - Exclude

Lint/ConstantDefinitionInBlock:
  Enabled: false

Style/OneClassPerFile:
  Enabled: false
