AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

inherit_gem:
  foobara-rubocop-rules:
    - rules/*

Naming/FileName:
  inherit_mode:
    merge:
      - Exclude

Lint/ConstantDefinitionInBlock:
  Enabled: false

Style/OneClassPerFile:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyClassDefinition:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

Rake/ClassDefinitionInTask:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false

RSpec/PredicateMatcher:
  Enabled: false
