#!/usr/bin/env ruby

# require "pry"
# require "pry-byebug"

puts 'Hello, World!'

def ractor
  Ractor.new do
    i = receive
    sleep 5
    i * i
  end
end

class Promise
  attr_accessor :then, :rescue, :ensure

  def initialize(ractor, *args)
    Ractor.new(ractor, *args) do |ractor, *args|
      port = Ractor::Port.new

      ractor.monitor(port)

      event = port.receive

      case event
      when :exited

        self.then&.call(ractor.value)
        binding.pry
        asdf
      when :aborted
        binding.pry
        error&.call(asdf)
        asdfsdf
      else
        raise "wtf"
      end
    ensure
      self.ensure&.call(ractor)
    end

    ractor.send(*args)
  end

  def then(&block)
    self.then = block
  end

  def ensure(&block)
    self.ensure = block
  end

  def rescue(&block)
    self.rescue = block
  end
end

r = ractor
Promise.new(ractor, 10).then { |i| "it works! Got #{i}!" }

puts r.value
