require "simplecov"

command_name = ENV["SHMACTOR"] == "true" ? "shmactor" : "ractor"

SimpleCov.root "#{__dir__}/../../"
SimpleCov.command_name command_name
SimpleCov.coverage_dir "coverage/#{command_name}"

SimpleCov.start do
  add_filter "spec/support/"
  enable_coverage :branch
  # This avoids printing out info about coverage generated by HTTPFormatter
  formatter Class.new { def format(_result) = nil }
end
