#!/usr/bin/env ruby

require_relative "../src/ractorized_object"

class Doubler < RactorizedObject
  def set(i)
    @i = i
  end

  def get
    @i
  end

  def double
    @i *= 2
  end
end

d = Doubler.new
d.set(10)
d.double
puts d.get

sleep 2
