#!/usr/bin/env ruby

require "bigdecimal"
require "ractorize"

class BigDecimal
  def to_s
    s = inspect
    match = /\A(-?[.\d]{8})\d+(e-?\d+)\z/.match(s)
    match ? "#{match[1]}#{match[2]}" : s
  end
end

srand(0)

CONCURRENCY = 3
# Is this basically Math::E or related?? And just off a bit due to randomness?
RANDOM_NUMBER_UPPER_BOUND = 2.78
RANDOM_NUMBERS = 25_000.times.map { BigDecimal(rand * RANDOM_NUMBER_UPPER_BOUND) }

class Productizer
  attr_accessor :product

  def initialize = self.product = 1
  def multiply(integer) = self.product *= integer
end

def multiply_all(productizer_class)
  productizers = CONCURRENCY.times.map { productizer_class.new }

  RANDOM_NUMBERS.each.with_index do |number, index|
    productizers[index % CONCURRENCY].multiply(number)
  end

  puts productizers.map(&:product).inject(:*)
  puts
end

puts "running non-ractorized productizer"
multiply_all(Productizer)

puts "running ractorized productizer"
multiply_all(Ractorize[Productizer])
