#!/usr/bin/env ruby

# require "pry"
# require "pry-byebug"

require_relative "../src/ractorize"
require_relative "../src/ractorize_instances"

class Doubler
  def set(integer)
    puts "in real #set"
    @i = integer
  end

  def get = @i
  def double = @i *= 2
end

# d = Doubler.new
# d.set(5)
# d.double
# puts d.get

Ractorize.ractorize_instances(Doubler)

d = Doubler.new
require "pry"
d.set(15)
sleep 5
puts "done setting"
sleep 5
d.double
sleep 5
puts d.get
