#!/usr/bin/env ruby

# require "pry"
# require "pry-byebug"

require_relative "../src/ractorize"

class Doubler
  def set(integer)
    @i = integer
  end

  def get
    @i
  end

  def double
    @i *= 2
  end
end

doubler = Doubler.new
d = Ractorize[doubler]

d.set(10)
d.double
puts d.get

doubler = Doubler.new
d = Ractorize[doubler]

d.set(100)
d.double
puts d.get
