#!/usr/bin/env ruby

# require "pry"
# require "pry-byebug"

require_relative "../src/ractorized"

class Doubler
  def set(integer)
    @i = integer
  end

  def get
    @i
  end

  def double
    @i *= 2
  end
end

RactorizedDoubler = Ractorized[Doubler]

d = RactorizedDoubler.new

d.set(10)
d.double
puts d.get

d = RactorizedDoubler.new

sleep 2
puts "setting async"
d.set_async(100)
puts "doubling async"
d.double_async
puts "done doubling, asking for value"
puts d.get_async.receive

sleep 2
