#!/usr/bin/env ruby

# require "pry"
# require "pry-byebug"

require_relative "../src/ractorize"

class Doubler
  def set(integer)
    @i = integer
  end

  def get
    @i
  end

  def double
    @i *= 2
  end
end

doubler = Doubler.new
puts "doubler.object_id"
puts doubler.object_id
d = Ractorize.ractorize(doubler)

d.set(10)
d.double
puts d.get

sleep 5

doubler = Doubler.new
puts "doubler.object_id"
puts doubler.object_id
d = Ractorize.ractorize(doubler)

sleep 2
d.set(100)
d.double
puts "done doubling, asking for value"
puts d.get

sleep 2
