#!/usr/bin/env ruby

require "timeout"

puts Ruby::VERSION

def ractor_and_port_counts
  total_ractor_count = total_ractor_port_count = open_ractor_count = open_ractor_port_count = 0

  ObjectSpace.each_object do |object|
    case object
    when Ractor
      total_ractor_count += 1
      open_ractor_count += 1 unless object.default_port.closed?
    when Ractor::Port
      total_ractor_port_count += 1
      open_ractor_port_count += 1 unless object.closed?
    end
  end

  [total_ractor_count, open_ractor_count, total_ractor_port_count, open_ractor_port_count]
end

def show_ractor_counts
  10.times do
    GC.start
    sleep 0.01
  end
  pp ractor_and_port_counts
end

def finalize_proc
  proc do |id|
    puts "going to clean up!! #{id}"
    CLEANUP_RACTOR << [:clean_up, id].freeze
  rescue
    puts "hmmm cleanup ractor already closed??"
    Ractor::ClosedError
  end
end

CLEANUP_RACTOR = Ractor.new do
  id_to_portlike = ObjectSpace::WeakMap.new

  loop do
    action = object_or_id = port_like = return_port = nil
    action, object_or_id, port_like, return_port = receive

    case action
    when :close
      close
      break
    when :add
      id_to_portlike[object_or_id.object_id] = port_like
      port_like = nil
      ObjectSpace.define_finalizer(object_or_id, &finalize_proc)
      object_or_id = nil
      return_port.send(object_or_id, move: true)
    when :clean_up
      puts "going to cleanup #{object_or_id}!"
      port_like = id_to_portlike[object_or_id]

      if port_like
        puts "it has port-like #{port_like}"
        begin
          puts "attempting close!"
          port_like << :close
          puts "worked!"
        rescue Ractor::ClosedError
          puts "failed to close! already closed??"
        end
        port_like = nil
      else
        puts "it has no port-like"
      end
    else
      raise "wtf, can't handle #{action}"
    end
  end

  nil
end

class Wrapper
  attr_reader :ractor

  def initialize(object)
    @ractor = Ractor.new do
      receive
      loop { break if receive == :close }
    end

    @ractor.send(object, move: true)

    CLEANUP_RACTOR << [:add, self, @ractor]
  end
end

class Outer
  def initialize = @inner = Wrapper.new(Inner.new)
end

class Inner; end

show_ractor_counts

outer = Wrapper.new(Outer.new)
show_ractor_counts

outer = nil

# Removing the following line makes it so it only segfaults sometimes instead of everytime
show_ractor_counts

puts "will close cleanup ractor..."
CLEANUP_RACTOR << :close
CLEANUP_RACTOR = nil

begin
  Timeout.timeout(5) do
    show_ractor_counts
  end
rescue Timeout::Error
end

show_ractor_counts
