#!/usr/bin/env ruby

require "bundler/setup"
require "irb"
require "ractorize"

def ractor_and_port_counts
  total_ractor_count = 0
  total_ractor_port_count = 0
  open_ractor_count = 0
  open_ractor_port_count = 0

  ObjectSpace.each_object do
    case it
    when Ractor
      total_ractor_count += 1
      open_ractor_count += 1 unless it.default_port.closed?
    when Ractor::Port
      total_ractor_port_count += 1
      open_ractor_port_count += 1 unless it.closed?
    end
  end

  [total_ractor_count, open_ractor_count, total_ractor_port_count, open_ractor_port_count]
end

pp ractor_and_port_counts

require "weakref"

port = Ractor::Port.new
t = Ractorize::Thunk.new(port)

20.times do
  GC.start
  ractor_and_port_counts
end

pp ractor_and_port_counts

puts "setting weakrefs"
port = WeakRef.new(port)
t = WeakRef.new(t)

20.times do
  GC.start
  ractor_and_port_counts
end

pp ractor_and_port_counts

puts "closing port with weakrefs"
port.close

20.times do
  GC.start
  ractor_and_port_counts
end

pp ractor_and_port_counts

puts "going to call abandon"
t.abandon!
puts "abandon done"

20.times do
  GC.start
  ractor_and_port_counts
end

pp ractor_and_port_counts
