#!/usr/bin/env ruby

require "bundler/setup"
require "irb"
require "ractorize"

class Doubler
  def set(integer) = @i = integer
  def get = @i
  def double = @i *= 2
end

def ractor_and_port_counts
  total_ractor_count = 0
  total_ractor_port_count = 0
  open_ractor_count = 0
  open_ractor_port_count = 0

  ObjectSpace.each_object do
    case it
    when Ractor
      total_ractor_count += 1
      open_ractor_count += 1 unless it.default_port.closed?
    when Ractor::Port
      total_ractor_port_count += 1
      open_ractor_port_count += 1 unless it.closed?
    end
  end

  [total_ractor_count, open_ractor_count, total_ractor_port_count, open_ractor_port_count]
end

pp ractor_and_port_counts

doubler = Ractorize[Doubler].new

pp ractor_and_port_counts
GC.start
pp ractor_and_port_counts

doubler.set(10)

pp ractor_and_port_counts
GC.start
pp ractor_and_port_counts

doubler = nil

GC.start
pp ractor_and_port_counts
GC.start
pp ractor_and_port_counts

puts "at bottom of script"
